--- #YAML:1.0
name:               Catalyst-Plugin-Server-JSONRPC
version:            0.07
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.66
    Catalyst::Plugin::Server:  0.01
    JSON:                 2.0
    JSON::RPC::Common:    0.03
    MRO::Compat:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
